FROM python:3.13.5-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV DB_PATH=/app/data/shorturl.db

VOLUME /app/data

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
